# Generated by Django 6.0.5 on 2026-05-25 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='source_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='normalizedrecord',
            name='activity_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='normalizedrecord',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='normalizedrecord',
            name='raw_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ingestion.rawrecord'),
        ),
        migrations.AlterField(
            model_name='normalizedrecord',
            name='scope',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='normalizedrecord',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='normalizedrecord',
            name='unit',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
