# Generated by Django 6.0.5 on 2026-05-25 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_alter_datasource_company_and_more'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrecord',
            name='approved',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='reviewrecord',
            name='record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ingestion.normalizedrecord'),
        ),
        migrations.AlterField(
            model_name='reviewrecord',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
